// Utilities
import { defineStore } from 'pinia'
import { article } from './article'
export const useAppStore = defineStore('app', {
  state: () => ({
    workshopdata : [{value :1, title : "ATELCO"},{value :2, title : "ATELIER ELECTRIQUE"},{value :3, title : "ATELIER MECANIQUE"},{value :4, title : "BATIMENTS"},{value :5, title : "BATTAGE"},{value :6, title : "BLANCHISSERIE"},{value :7, title : "CASSE CROUTE"},{value :8, title : "CMT"},{value :9, title : "COMMERCIALE"},{value :10, title : "COMPAGNIE MALAGASY DE TEX"},{value :11, title : "COMPRESSE GAZE"},{value :12, title : "COMPTA"},{value :13, title : "COTON HYDROPHILE"},{value :14, title : "DG"},{value :15, title : "ECOTEINTURE"},{value :16, title : "EFFILOCHAGE"},{value :17, title : "EMBALLAGE"},{value :18, title : "ETS RAHARINIAINA"},{value :19, title : "FFF ASSEMBLAGE"},{value :20, title : "FFF BOBINAGE"},{value :21, title : "FFF FILATURE"},{value :22, title : "FFF MAGASIN"},{value :23, title : "FFF PREPARATION"},{value :24, title : "FILATURE 2"},{value :25, title : "FINITION"},{value :26, title : "FLT"},{value :27, title : "FOURNISSEUR EXTERIEUR"},{value :28, title : "GRAZE"},{value :29, title : "IMPRESSION"},{value :30, title : "INFORMATIQUE"},{value :31, title : "J11"},{value :32, title : "LIBRE"},{value :33, title : "LOGISTIQUE"},{value :34, title : "MAGASIN CENTRAL"},{value :35, title : "MAGASIN D'USINE"},{value :36, title : "MATIERES PREMIERES"},{value :37, title : "MCV"},{value :38, title : "MECHE A BOUGIE"},{value :39, title : "MENUISERIE"},{value :40, title : "MERCERISAGE"},{value :41, title : "OURDISSAGE"},{value :42, title : "PADELLE"},{value :43, title : "PERSONNEL"},{value :44, title : "PLOMBERIE"},{value :45, title : "PRESSE"},{value :46, title : "RABENIJANONANA JONNAH M."},{value :47, title : "RANDRIANINDRINA Jean Jacques"},{value :48, title : "RASOAZANAMANANA Sahondra"},{value :49, title : "SEBRO"},{value :50, title : "SECRETARIAT"},{value :51, title : "SECURITE"},{value :52, title : "TEINTURE"},{value :53, title : "TISSAGE 1"},{value :54, title : "TISSAGE 2"},{value :55, title : "TRANSIT"},{value :56, title : "TRANSPORT"},{value :57, title : "TRICOTAGE"},{value :58, title : "TRICOTAGE FESTIVAL"}],
    ActiveworkshopSource : '',
    color : [
      "ABRICOT",
      "ACAJOU",
      "AIGUE-MARINE",
      "ALEZAN (CHEVAUX)",
      "AMANDE",
      "AMARANTE",
      "AMBRE",
      "AMÉTHYSTE",
      "ANTHRACITE",
      "AQUILAIN (CHEVAUX)",
      "ARDOISE",
      "ARGENT (HÉRALDIQUE)",
      "AUBERGINE",
      "AUBURN (CHEVEUX)",
      "AURORE",
      "AVOCAT",
      "AZUR",
      "AZUR (HÉRALDIQUE)",
      "BAILLET (CHEVAUX, VIEILLI)",
      "BASANÉ (TEINT)",
      "BEIGE OU BUREAU",
      "BEURRE",
      "BIS",
      "BISQUE",
      "BISTRE",
      "BITUME (PIGMENT)",
      "BLANC",
      "BLANC CASSÉ",
      "BLANC LUNAIRE",
      "BLÉ",
      "BLEU",
      "BLEU ACIER",
      "BLEU BARBEAU OU BLEUET",
      "BLEU CANARD",
      "BLEU CÉLESTE",
      "BLEU CHARRETTE",
      "BLEU CIEL",
      "BLEU DE COBALT (PIGMENT)",
      "BLEU DE PRUSSE (PIGMENT), DE BERLIN OU BLEU HUSSARD",
      "BLEU ÉLECTRIQUE",
      "BLEU GIVRÉ",
      "BLEU KLEIN",
      "BLEU MAJORELLE",
      "BLEU MARINE",
      "BLEU NUIT",
      "BLEU OUTREMER",
      "BLEU PAON",
      "BLEU PERSAN",
      "BLEU PÉTROLE",
      "BLEU ROI OU DE FRANCE",
      "BLEU TURQUIN",
      "BLOND (CHEVEUX)",
      "BLOND VÉNITIEN (CHEVEUX)",
      "BORDEAUX",
      "BOUTON D'OR",
      "BRIQUE",
      "BRONZE",
      "BROU DE NOIX",
      "BRUN",
      "CACA D'OIE",
      "CACAO",
      "CACHOU (PIGMENTS)",
      "CÆRULEUM",
      "CAFÉ",
      "CAFÉ AU LAIT",
      "CANNELLE",
      "CAPUCINE",
      "CARAMEL (PIGMENTS)",
      "CARMIN (PIGMENT)",
      "CARMIN D'ALIZARINE (PIGMENT PR83)",
      "CAROTTE",
      "CHAMOIS",
      "CHARTREUSE",
      "CHÂTAIN (CHEVEUX)",
      "CHAUDRON",
      "CHOCOLAT",
      "CINABRE (PIGMENT)",
      "CITROUILLE",
      "COQUILLE D'ŒUF",
      "CORAIL",
      "CRAMOISI",
      "CRÈME",
      "CUISSE DE NYMPHE",
      "CUIVRE",
      "CYAN",
      "ÉCARLATE",
      "ÉCRU",
      "ÉMERAUDE",
      "FAUVE",
      "FLAVE",
      "FRAISE",
      "FRAISE ÉCRASÉE",
      "FRAMBOISE",
      "FUCHSIA",
      "FUMÉE",
      "GARANCE (PIGMENT)",
      "GLAUQUE",
      "GLYCINE",
      "GRÈGE",
      "GRENADINE",
      "GRENAT",
      "GRIS",
      "GRIS ACIER",
      "GRIS DE PAYNE (MÉLANGE DE PIGMENTS)",
      "GRIS FER",
      "GRIS PERLE",
      "GROSEILLE",
      "GUÈDE OU PASTEL DES TEINTURIERS (PIGMENT)",
      "GUEULES (HÉRALDIQUE)",
      "HÉLIOTROPE",
      "INCARNAT",
      "INDIGO",
      "INDIGO (TEINTURE)",
      "ISABELLE",
      "IVOIRE",
      "JAUNE",
      "JAUNE CANARI",
      "JAUNE CITRON",
      "JAUNE D'OR",
      "JAUNE DE COBALT OU AURÉOLIN (PIGMENT)",
      "JAUNE DE MARS (PIGMENT)",
      "JAUNE DE NAPLES (PIGMENT)",
      "JAUNE IMPÉRIAL",
      "JAUNE MIMOSA",
      "KAKI",
      "LAPIS-LAZULI",
      "LAVALLIÈRE (RELIURE)",
      "LAVANDE",
      "LIE DE VIN",
      "LILAS",
      "LIME OU VERT CITRON",
      "LIN",
      "MAGENTA",
      "MAÏS",
      "MALACHITE",
      "MANDARINE",
      "MARRON",
      "MASTIC",
      "MAUVE (COULEUR)",
      "MENTHE",
      "MOUTARDE",
      "NACARAT",
      "NANKIN",
      "NOIR",
      "NOIR ANIMAL (PIGMENT)",
      "NOIR D'ANILINE (PIGMENT)",
      "NOIR D'IVOIRE (PIGMENT)",
      "NOIR DE CARBONE (PIGMENT)",
      "NOIR DE FUMÉE (PIGMENT)",
      "NOISETTE",
      "OCRE (PIGMENT)",
      "OCRE ROUGE (PIGMENT)",
      "OLIVE",
      "OR",
      "ORANGE",
      "ORANGE BRÛLÉ",
      "ORCHIDÉE",
      "ORPIMENT (PIGMENT)",
      "PAILLE",
      "PARME",
      "PELURE D'OIGNON (ŒNOLOGIE)",
      "PERVENCHE",
      "PISTACHE",
      "POIL DE CHAMEAU",
      "PONCEAU OU COQUELICOT",
      "POURPRE (HÉRALDIQUE)",
      "PRASIN",
      "PRUNE",
      "PUCE",
      "ROSE",
      "ROSE MOUNTBATTEN",
      "ROUGE",
      "ROUGE ANGLAIS",
      "ROUGE CARDINAL",
      "ROUGE CERISE",
      "ROUGE D'ANDRINOPLE",
      "ROUGE DE FALUN (PIGMENT)",
      "ROUGE FEU",
      "ROUGE FEU",
      "ROUGE SANG",
      "ROUGE TOMETTE",
      "ROUILLE",
      "ROUX",
      "RUBIS",
      "SABLE",
      "SABLE (HÉRALDIQUE)",
      "SAFRE",
      "SANG DE BŒUF",
      "SANGUINE",
      "SAPHIR",
      "SARCELLE",
      "SAUMON",
      "SÉPIA (PIGMENT)",
      "SINOPLE (HÉRALDIQUE)",
      "SMALT (PIGMENT)",
      "SMARAGDIN (PIGMENT)",
      "SOUFRE",
      "SOURIS",
      "TABAC",
      "TAUPE",
      "TERRE D'OMBRE",
      "TERRE DE SIENNE (PIGMENT)",
      "TERRE DE SIENNE BRÛLÉE (PIGMENT)",
      "TOMATE",
      "TOPAZE",
      "TOURTERELLE OU COLOMBIN",
      "TURQUOISE",
      "VANILLE",
      "VERMEIL",
      "VERMILLON",
      "VERT",
      "VERT BOUTEILLE",
      "VERT CÉLADON",
      "VERT D'EAU",
      "VERT DE CHROME",
      "VERT DE HOOKER",
      "VERT DE VESSIE",
      "VERT ÉPINARD",
      "VERT IMPÉRIAL",
      "VERT LICHEN",
      "VERT PERROQUET",
      "VERT POIREAU",
      "VERT POMME",
      "VERT PRAIRIE",
      "VERT PRINTEMPS",
      "VERT SAPIN",
      "VERT SAUGE",
      "VERT TILLEUL",
      "VERT VÉRONÈSE (PIGMENT)",
      "VERT-DE-GRIS (PIGMENT)",
      "VERT-JAUNE",
      "VIOLET",
      "VIOLET D'ÉVÊQUE",
      "VIOLINE (PIGMENT)",
      "VIRIDE (PIGMENT)",
      "ZINZOLIN"
   ],
   articles: article
  }),
})
