export default function Workshop(){
  const getContent = () => {
    let data=[{value :1, title : "ATELCO"},{value :2, title : "ATELIER ELECTRIQUE"},{value :3, title : "ATELIER MECANIQUE"},{value :4, title : "BATIMENTS"},{value :5, title : "BATTAGE"},{value :6, title : "BLANCHISSERIE"},{value :7, title : "CASSE CROUTE"},{value :8, title : "CMT"},{value :9, title : "COMMERCIALE"},{value :10, title : "COMPAGNIE MALAGASY DE TEX"},{value :11, title : "COMPRESSE GAZE"},{value :12, title : "COMPTA"},{value :13, title : "COTON HYDROPHILE"},{value :14, title : "DG"},{value :15, title : "ECOTEINTURE"},{value :16, title : "EFFILOCHAGE"},{value :17, title : "EMBALLAGE"},{value :18, title : "ETS RAHARINIAINA"},{value :19, title : "FFF ASSEMBLAGE"},{value :20, title : "FFF BOBINAGE"},{value :21, title : "FFF FILATURE"},{value :22, title : "FFF MAGASIN"},{value :23, title : "FFF PREPARATION"},{value :24, title : "FILATURE 2"},{value :25, title : "FINITION"},{value :26, title : "FLT"},{value :27, title : "FOURNISSEUR EXTERIEUR"},{value :28, title : "GRAZE"},{value :29, title : "IMPRESSION"},{value :30, title : "INFORMATIQUE"},{value :31, title : "J11"},{value :32, title : "LIBRE"},{value :33, title : "LOGISTIQUE"},{value :34, title : "MAGASIN CENTRAL"},{value :35, title : "MAGASIN D'USINE"},{value :36, title : "MATIERES PREMIERES"},{value :37, title : "MCV"},{value :38, title : "MECHE A BOUGIE"},{value :39, title : "MENUISERIE"},{value :40, title : "MERCERISAGE"},{value :41, title : "OURDISSAGE"},{value :42, title : "PADELLE"},{value :43, title : "PERSONNEL"},{value :44, title : "PLOMBERIE"},{value :45, title : "PRESSE"},{value :46, title : "RABENIJANONANA JONNAH M."},{value :47, title : "RANDRIANINDRINA Jean Jacques"},{value :48, title : "RASOAZANAMANANA Sahondra"},{value :49, title : "SEBRO"},{value :50, title : "SECRETARIAT"},{value :51, title : "SECURITE"},{value :52, title : "TEINTURE"},{value :53, title : "TISSAGE 1"},{value :54, title : "TISSAGE 2"},{value :55, title : "TRANSIT"},{value :56, title : "TRANSPORT"},{value :57, title : "TRICOTAGE"},{value :58, title : "TRICOTAGE FESTIVAL"}];
    //let data=[{value :1, title : "ATELCO"},{value :2, title : "ATELIER ELECTRIQUE"}]
    return data;
  }

  return {
    getContent,
  }
}
